-- 01-users.sql — demo users, covering every account state the schema supports.
--
-- ┌─────────────────────────────────────────────────────────────────────────────┐
-- │ PASSWORD: supplied BY THE CALLER, never stored in this file. The caller     │
-- │ passes `-v demo_password_hash=<bcrypt>`; the guard below aborts with a       │
-- │ non-zero exit when it is missing or empty. See README.md → Demo credentials. │
-- └─────────────────────────────────────────────────────────────────────────────┘
--
-- WHY THE HASH IS A REQUIRED VARIABLE AND NOT A LITERAL. This file used to embed
-- one committed bcryptjs literal (12 rounds — the cost `lib/auth.ts` uses) shared
-- by all twelve rows. Because that literal lived in git, re-applying this file to a
-- non-local database silently re-installed a password anyone with repository access
-- can read: on production that is twelve working logins whose plaintext is public.
-- Rotating afterwards was a separate manual step, and a step that can be forgotten
-- is not a control. The hash is now a required input, so the failure mode is a loud
-- abort rather than a silently weak credential.
--
--   local  → prisma/demo/local/all-local.sql supplies the committed dev hash
--   server → the caller must pass a server-only hash (README.md §7.3)
--
-- FAIL-CLOSED GUARD — probed, not assumed (psql 18.6):
--   unset → exit 3, "demo_password_hash is required"
--   empty → exit 3, "demo_password_hash must be a non-empty bcrypt hash"
--   given → exit 0
-- Two mechanisms, because neither alone is sufficient:
--   * definedness — `\if :{?demo_password_hash}`. A bare :'var' reference is NOT
--     relied on: psql happens to leave it unreplaced (a syntax error), but that is
--     version-dependent and reports an opaque parse failure instead of naming the
--     variable. `\quit` is NOT used either: it ignores an exit-code argument
--     ("extra argument 3 ignored") and still exits 0, so it does not fail closed.
--   * emptiness — the value is loaded into a session GUC, because psql does not
--     interpolate :'...' inside a dollar-quoted body, so a DO block cannot read the
--     variable directly. `set_config(..., false)` keeps it session-scoped.
--
-- IDS ARE EXPLICIT AND MANDATORY. Live DDL check: `"User".id` is `text NOT NULL`
-- with NO database default, because Prisma's `@default(uuid())` is generated by
-- the Prisma *client*, not by Postgres. Omitting an id here fails the whole INSERT.
-- The reserved namespace `00000000-de30-4000-8000-*` is what makes teardown exact.
--
-- Idempotent: re-running updates the same 12 rows and creates none. `ON CONFLICT
-- (id)` is the only target needed — email is UNIQUE but ids are deterministic, so
-- a re-run can never reach the email constraint with a different id.

\set ON_ERROR_STOP on

-- ── FAIL-CLOSED GUARD: exactly one of the two blocks below must raise. ────────
\if :{?demo_password_hash}
\else
DO $guard$
BEGIN
  RAISE EXCEPTION 'demo_password_hash is required - pass -v demo_password_hash=<bcrypt>, or use prisma/demo/local/all-local.sql for local development';
END
$guard$;
\endif

-- Loads the value into a session GUC so the DO block below can inspect it (psql
-- does not interpolate :'...' inside dollar quotes). `\gset` keeps it silent.
SELECT set_config('demo.password_hash', :'demo_password_hash', false) AS _loaded \gset

DO $guard$
BEGIN
  IF coalesce(current_setting('demo.password_hash', true), '') = '' THEN
    RAISE EXCEPTION 'demo_password_hash must be a non-empty bcrypt hash';
  END IF;

  -- Shape check: a whitespace-only or non-bcrypt value is caller-supplied junk.
  -- It installs no *known* credential, but it does install an *unusable* one on
  -- every demo account - a silent lockout that no lint, test or healthcheck sees.
  IF current_setting('demo.password_hash') !~ '^\$2[aby]\$[0-9]{2}\$' THEN
    RAISE EXCEPTION 'demo_password_hash must be bcrypt-shaped (^$2[aby]$NN$...); refusing to seed an unusable hash';
  END IF;
END
$guard$;

INSERT INTO "User" (
  id, name, email, "emailVerified", password,
  "invalid_login_attempts", "lockedAt", "disabledAt", "platformRole",
  "createdAt", "updatedAt"
) VALUES
  -- Platform admin. `platformRole` is the ONLY gate for /admin and /api/admin/*
  -- (`lib/guardPlatformAdmin.ts` reads the FRESH database value on every call).
  -- Deliberately NOT a member of any team: the admin console and team roles are
  -- independent axes in this product.
  ('00000000-de30-4000-8000-000000000002', 'Demo Platform Admin', 'demo-platform-admin@demo.smartapro.com',
   now() - interval '60 days', :'demo_password_hash',
   0, NULL, NULL, 'PLATFORM_ADMIN'::"PlatformRole",
   now() - interval '60 days', now() - interval '60 days'),

  -- Ordinary verified users across the three demo teams.
  ('00000000-de30-4000-8000-000000000001', 'Demo Owner', 'demo-owner@demo.smartapro.com',
   now() - interval '40 days', :'demo_password_hash',
   0, NULL, NULL, NULL, now() - interval '40 days', now() - interval '40 days'),

  ('00000000-de30-4000-8000-000000000003', 'Demo Team Admin', 'demo-admin@demo.smartapro.com',
   now() - interval '38 days', :'demo_password_hash',
   0, NULL, NULL, NULL, now() - interval '38 days', now() - interval '38 days'),

  ('00000000-de30-4000-8000-000000000004', 'Demo Member', 'demo-member@demo.smartapro.com',
   now() - interval '35 days', :'demo_password_hash',
   0, NULL, NULL, NULL, now() - interval '35 days', now() - interval '35 days'),

  ('00000000-de30-4000-8000-00000000000a', 'Demo Second Member', 'demo-member2@demo.smartapro.com',
   now() - interval '30 days', :'demo_password_hash',
   0, NULL, NULL, NULL, now() - interval '30 days', now() - interval '30 days'),

  ('00000000-de30-4000-8000-00000000000b', 'Demo Owner Two', 'demo-owner2@demo.smartapro.com',
   now() - interval '28 days', :'demo_password_hash',
   0, NULL, NULL, NULL, now() - interval '28 days', now() - interval '28 days'),

  ('00000000-de30-4000-8000-000000000009', 'Demo ERP Owner', 'demo-erp-owner@demo.smartapro.com',
   now() - interval '25 days', :'demo_password_hash',
   0, NULL, NULL, NULL, now() - interval '25 days', now() - interval '25 days'),

  -- Awaiting confirmation: `emailVerified IS NULL`. The credentials provider
  -- refuses sign-in for this row while CONFIRM_EMAIL=true, which is the state the
  -- "check your inbox" copy is written for.
  ('00000000-de30-4000-8000-000000000005', 'Demo Unverified', 'demo-unverified@demo.smartapro.com',
   NULL, :'demo_password_hash',
   0, NULL, NULL, NULL, now() - interval '10 days', now() - interval '10 days'),

  -- Account lockout. `lib/accountLock.ts` locks when `lockedAt` is set AND
  -- `invalid_login_attempts >= env.maxLoginAttempts` (= 5; `MAX_LOGIN_ATTEMPTS=5`
  -- in .env, and the fallback in `lib/env.ts` is also 5). The counter is set to
  -- the ceiling on purpose — one below it would NOT be locked.
  ('00000000-de30-4000-8000-000000000006', 'Demo Locked', 'demo-locked@demo.smartapro.com',
   now() - interval '20 days', :'demo_password_hash',
   5, now() - interval '1 hour', NULL, NULL, now() - interval '20 days', now() - interval '1 hour'),

  -- Soft-disabled. `disabledAt` is checked by the sign-in path and by the admin
  -- console's user list; a non-NULL value means the account is refused.
  ('00000000-de30-4000-8000-000000000007', 'Demo Disabled', 'demo-disabled@demo.smartapro.com',
   now() - interval '18 days', :'demo_password_hash',
   0, NULL, now() - interval '2 days', NULL, now() - interval '18 days', now() - interval '2 days'),

  -- Verified, healthy, and deliberately on NO team. Proves the "create or join a
  -- team" empty state without needing a fresh signup.
  ('00000000-de30-4000-8000-000000000008', 'Demo No Team', 'demo-noteam@demo.smartapro.com',
   now() - interval '15 days', :'demo_password_hash',
   0, NULL, NULL, NULL, now() - interval '15 days', now() - interval '15 days'),

  -- Target of the PENDING invitation written by 03-invitations.sql, so the
  -- invitation row and the account it points at can be inspected together.
  ('00000000-de30-4000-8000-00000000000c', 'Demo Invitee', 'demo-invitee@demo.smartapro.com',
   now() - interval '12 days', :'demo_password_hash',
   0, NULL, NULL, NULL, now() - interval '12 days', now() - interval '12 days')
ON CONFLICT (id) DO UPDATE SET
  name                   = EXCLUDED.name,
  email                  = EXCLUDED.email,
  "emailVerified"        = EXCLUDED."emailVerified",
  password               = EXCLUDED.password,
  "invalid_login_attempts" = EXCLUDED."invalid_login_attempts",
  "lockedAt"             = EXCLUDED."lockedAt",
  "disabledAt"           = EXCLUDED."disabledAt",
  "platformRole"         = EXCLUDED."platformRole",
  "updatedAt"            = EXCLUDED."updatedAt";

\echo '==> 01-users.sql: 12 demo users ensured'
